// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TryingSolveErrorInSaveDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TryingSolveErrorInSaveDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202303271529459_TryingSolveErrorInSaveDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
